# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ar-audit-tracer}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Schweizer"]
  s.date = %q{2010-11-27}
  s.description = %q{Handles ActiveRecord authors in the same way as timstamps.}
  s.email = %q{contact@verticonaut.me}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "ar-audit-tracer.gemspec",
    "lib/ar-audit-tracer.rb",
    "lib/concern/audit/author.rb",
    "test/concern/audit/author_test.rb",
    "test/helper.rb",
    "test/resources/models.rb",
    "test/resources/schema.rb",
    "test/test_ar-audit-tracer.rb"
  ]
  s.homepage = %q{http://github.com/verticonaut/ar-audit-tracer}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Track creator/modifiers of you AR Models similar to timestamps.}
  s.test_files = [
    "test/concern/audit/author_test.rb",
    "test/helper.rb",
    "test/resources/models.rb",
    "test/resources/schema.rb",
    "test/test_ar-audit-tracer.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

