# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ar-audit-tracer}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Martin Schweizer"]
  s.date = %q{2010-09-22}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{martin.schweizer@awd.ch}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/ar-audit-tracer.rb",
     "lib/concern/audit/author.rb",
     "test/concern/audit/author_test.rb"
  ]
  s.homepage = %q{http://github.com/verticonaut/ar-audit-tracer}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "test/concern/audit/author_test.rb",
     "test/helper.rb",
     "test/resources/models.rb",
     "test/resources/schema.rb",
     "test/test_ar-audit-tracer.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

